apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: gcr.io/hardy-messenger-434723-i9/nginx-proxy:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
  namespace: nginx-proxy
  labels:
    app: nginx-proxy
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80