apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp
  labels:
    id: c0905643
    app: wordpress
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      id: c0905643
      app: wordpress
      env: dev
  template:
    metadata:
      labels:
        id: c0905643
        app: wordpress
        env: dev
    spec:
      containers:
      - name: wordpress
        image: gcr.io/hardy-messenger-434723-i9/wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "db-service:3306"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: WORDPRESS_DB_USER
          value: "user"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: password
