apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp
  labels:
    "id": "c0905643"
    app: wordpress
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      "id": "c0905643"
  template:
    metadata:
      labels:
        id: c0905643
        app: wordpress
        env: dev
    spec:
      containers:
      - name: wordpress
        image: gcr.io/hardy-messenger-434723-i9/wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb-service.db.svc.cluster.local
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wp-db-secrets
              key: db-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wp-db-secrets
              key: db-password
        - name: WORDPRESS_DB_NAME
          value: wordpress
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wp
spec:
  type: NodePort
  selector:
    "id": "c0905643"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
