apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        id: c0905643
        app: mariadb
        env: dev
    spec:
      containers:
        - name: mariadb
          image: gcr.io/hardy-messenger-434723-i9/mariadb:latest
          envFrom:
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          ports:
            - containerPort: 3306
---
# Database Service
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: db
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306