apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: db
  labels:
    id: c0905643
    app: mariadb
    env: dev
type: Opaque
data:
  root-password: cGFzc3dvcmQ=
  user-password: cGFzc3dvcmQ=